### ISSUE TITLE
add `fortls` to brew

### ISSUE THREAD

**Issue by gnikit** [gnikit/fortls#196]

**Comment by awvwgk** [comment]
We can submit https://github.com/fortran-lang/homebrew-fortran/pull/13 to homebrew-core. Only thing needed is a proper test, can you post an example to start the language server and send a request, which is usable as a minimal test?

**Comment by gnikit** [comment]
I don't think we can "test" by running the actual server because it opens (and does not close) IO streams. We can run one-off commands via the `--debug_...` commands

**Comment by awvwgk** [comment]
Okay, let's try and see what the homebrew maintainers say. Do you want to give it a shot?

**Comment by gnikit** [comment]
Sure, would something like this work?

```sh
$ cat main.f90
program main
end program main
$ fortls --debug_filepath main.f90 --debug_symbols --debug_full_result

Testing "textDocument/documentSymbol" request:
  File = "main.f90"
[
  {
    "name": "main",
    "kind": 2,
    "location": {
      "uri": "main.f90",
      "range": {
        "start": {
          "line": 0,
          "character": 0
        },
        "end": {
          "line": 1,
          "character": 0
        }
      }
    }
  }
]
```
```

**Comment by awvwgk** [comment]
> Do you want to give it a shot?

Just remembered that homebrew doesn't like self-submissions (see https://docs.brew.sh/Acceptable-Formulae). I'll setup a PR later.

**Comment by gnikit** [comment]
Another problem might be that `fortls` has the ability to autoupdate, you have to `--disable_autoupdate` to stop that.

**Comment by awvwgk** [comment]
Can be closed, available now in `homebrew/core`.
