### ISSUE TITLE
feat: increase default Python recursion limit

### ISSUE THREAD

**Issue by 1JunGu** [gnikit/fortls#207]
**Describe the bug**
`Server initialization failed.
  Message: Error sending result: '<fortls.parse_fortran.FortranFile object at 0x7fddce1c8d60>'. Reason: 'RecursionError('maximum recursion depth exceeded while calling a Python object')'`

**To Reproduce**
`Initialising Language Server for workspace: *.F with command-line options: --enable_code_actions, --hover_signature, --use_signature_help, --lowercase_intrinsics, --nthreads=4, --incremental_sync`

Alternatively, you can try and describe the steps that you followed to encounter the bug:
1. Download fortls using conda, and download Modern Fortran in VS code
2. open my program directory, and click a Fortran file with suffix ".F"
3. See error

**Expected behavior**

**Screenshots & Animations**
If applicable, add screenshots or GIF/MP4 animations to help explain your problem.

**Setup information (please complete the following information):**
 - OS: Mac intel 2020
 - Python Version: 3.9
 - fortls Version: 2.13.0
 - Code editor used: VS Code
 - the Fortran extension for the code editor and its version: Modern Fortran v3.2.0

**Comment by 1JunGu** [comment]
I probably solve this question temporarily.
1. I add `sys.setrecursionlimit(3000)`  in the `fortls` shell command.
2. delete some unnecessary codes (may be a lot).
Then I restart the workspace, the Modern Fortran wouldn't issue any errors! Thanks for your excellent software for Fortran programmer!

**Comment by gnikit** [comment]
Yeah, I don't think we can change the recursion limit since it would greatly affect the performance and memory consumption of the language server. I don't remember the specifics on this but when I run into this around a year ago there was a non-trivial reason as to why I could not change it for fortls.
