### ISSUE TITLE
Wording suggestion - binary

### ISSUE THREAD

**Issue by ivan-pi** [gnikit/fortls#210]
Under the section Common installation problems (https://github.com/gnikit/fortls#common-installation-problems) it says:

> It is NOT recommended having fortls and fortran-language-server simultaneously installed, since they use the same binary name.

As far as I can understand, fortls is not a _binary_, but an _executable script_. My suggestion is to replace "binary" with "executable file name" if you agree. 

Sources:
* [Where is the difference between "binaries" and "executables" in the context of an executable program?](https://stackoverflow.com/questions/59826292/where-is-the-difference-between-binaries-and-executables-in-the-context-of-a)

**Comment by gnikit** [comment]
I think swapping with "executable" might be more appropriate. I'll change the docs.
