### ISSUE TITLE
Increase build-in keywords offer for autocomplete

### ISSUE THREAD

**Issue by gnikit** [gnikit/fortls#63]
Currently the Fortran keywords offered for autocompletion is a relatively small set of what is available in Fortran.
I would like to substantially increase that to make typing definitions less cumbersome.

**Comment by JHenneberg** [comment]
are you talking about `statements.json` or `intrinsic_funs.json`

**Comment by gnikit** [comment]
I think keywords.json works ok assuming you operate within the appropriate scope (not sure if keywords are missing from the file).
I was originally referring to statements.json but now looking back I can't recall what it was missing.

intrinsic_funs.json and intrinsic_mods.json should be complete to the newest GCC release + common GNU extensions
