### ISSUE TITLE
Request textDocument/implementation failed.

### ISSUE THREAD

**Issue by mdeberts** [gnikit/fortls#80]
If I simple do right click + "go to Implementations" within VsCode on mod(5,2) I get the following error
No .fortls file or changed settings (maybe I did something wrong without noticing but as far as I know I did not change anything)

```f08
program myprogram
   implicit none
   integer :: i
   i = mod(5,2)
end program myprogram
```

```log
[INFO - 16:02:21] fortls - Fortran Language Server 2.2.5 Initialized
[Error - 4:03:37 PM] Request textDocument/implementation failed.
  Message: 'NoneType' object has no attribute 'get_type'
  Code: -32603 
[object Object]
```

**Comment by gnikit** [comment]
Fixed in [v2.2.10](https://github.com/gnikit/fortls/releases/tag/v2.2.10)
